# -*- coding: utf-8 -*-

DEFAULT = 'DEFAULT'

BURSA_MARKET_ACE_MARKET = 'Ace Market'
BURSA_MARKET_LEAP_MARKET = 'Leap Market'
BURSA_MARKET_MAIN_MARKET = 'Main Market'
BURSA_MARKET_STRUCTURED_WARRANTS = 'Structured Warrants'
BURSA_MARKET_ETF = 'ETF'
BURSA_MARKET_BOND = 'Bond'

STOCK_DIRECTION_CLOSED = 'Closed'
STOCK_DIRECTION_DECREATED = 'Decreased'
STOCK_DIRECTION_INCREASED = 'Increased'
STOCK_DIRECTION_NO_CHANGE = 'No change'
